routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::middleware(['guest'])->group(function () {

    Route::get('/', 'PublicPageController@welcome')->name('welcome');
    // Visitors
    Route::get('sell/{id}', 'PublicPageController@SellView')->name('sell');
    Route::get('buy/{id}', 'PublicPageController@BuyView')->name('buy');
    //Waqas Changes
    Route::get('/email-verification', 'UserController@emailVerification')->name('emailVerification');
});
//Route::get('/deploy-923457286', 'Controller@deploy')->name('deploy');
// Default
Auth::routes(['verify' => false]);
Route::middleware(['auth'])->group(function () {
    //home
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/filter', 'HomeController@filter')->name('filter');
    // Admin
    Route::get('admin', 'PageController@viewAdmin')->name('admin');
    //Waqas Changes
    Route::get('findmenu_options', 'PageController@findmenu_options')->name('findmenu_options');
    Route::post('add_user_menu', 'PageController@add_user_menu')->name('add_user_menu');
    Route::get('brandupdate', 'PageController@brandupdate')->name('brandupdate');
    Route::post('brandupdate', 'PageController@brandupdate')->name('brandupdate');
    //Admin dropdown
    Route::get('wallet', 'PageController@wallet')->name('wallet');
    Route::get('UserAccess', 'PageController@userAccess')->name('UserAccess');
    Route::get('accountant', 'PageController@accountant')->name('accountant');
    Route::get('accountant/user/{id}', 'PageController@accountantUser')->name('User');
    Route::get('membership', 'PageController@membership')->name('membership');
    Route::get('userMembershipdetails', 'PageController@userMembershipdetails')->name('userMembershipdetails');
    Route::post('updateShareRate', 'PageController@updateShareRate')->name('updateShareRate');




    Route::get('CategorySetup', 'PageController@categorySetup')->name('categorySetup');
    Route::get('CategorySetup2', 'PageController@test')->name('test');
    Route::get('QueryScreen', 'PageController@queryscreen')->name('queryscreen');
    Route::post('TakeQuery', 'PageController@takeQuery')->name('takequery');
    Route::post('SaveQuery', 'PageController@saveQuery')->name('saveQuery');
    Route::post('DeleteQuery', 'PageController@deleteQuery')->name('deleteQuery');
    Route::post('SavePost', 'PageController@savePost')->name('savePost');
    Route::post('credit', 'PageController@credit')->name('credit');
    Route::post('transfer', 'PageController@transfer')->name('transfer');
    Route::post('cancelWithdrawRequest', 'PageController@cancelWithdrawRequest')->name('cancelWithdrawRequest');
    Route::post('approveWithdrawRequest', 'PageController@approveWithdrawRequest')->name('approveWithdrawRequest');
    Route::post('memberData', 'PageController@memberData')->name('memberData');
    Route::post('uploadMemberPdfFile', 'PageController@uploadMemberPdfFile')->name('uploadMemberPdfFile');
    Route::get('downloadMemberPdfFile', 'PageController@downloadMemberPdfFile')->name('downloadMemberPdfFile');
    Route::post('getIdNameList', 'PageController@getIdNameList')->name('getIdNameList');
    Route::post('OpacityUpdate', 'PageController@opacityUpdate')->name('opacityUpdate');
    Route::post('getEmailBasedData', 'PageController@getEmailBasedData')->name('getEmailBasedData');
    Route::post('getTransByDateRange', 'PageController@getTransByDateRange')->name('getTransByDateRange');
    Route::post('moveToExcel', 'PageController@moveToExcel')->name('moveToExcel');

    // Admin
    Route::get('admin', 'PageController@viewAdmin')->name('admin');
    Route::get('findmenu_options', 'PageController@findmenu_options')->name('findmenu_options');
    Route::post('add_user_menu', 'PageController@add_user_menu')->name('add_user_menu');
    Route::get('brandupdate', 'PageController@brandupdate')->name('brandupdate');
    Route::post('brandupdate', 'PageController@brandupdate')->name('brandupdate');
//Babar works 
    Route::get('/booking', 'BookingController@booking')->name('booking');
    // User Profile
    Route::get('/profile', 'UserController@showProfile')->name('profile');
    Route::get('/profile/{id}','UserController@showProfilewithid');
    Route::get('/userprofile', 'UserController@userProfile');
    Route::get('/userprofile/{id}', 'UserController@otherUserProfile')->name('otherUserProfile');
    Route::get('/about', 'UserController@about')->name('about');
    Route::post('/about/userProfile', 'UserController@aboutUserProfile');
    Route::get('generate-pdf','UserController@generatePDF');

    Route::post('/updateUserImage', 'UserController@updateCoverPic')->name('updateImage');
//matul
    Route::get('/user_access_search','PageController@user_access_search')->name('user_access_search');
    Route::get('/get_user_image_and_link','PageController@get_user_image_and_link')->name('get_user_image_and_link');
    //login_system by matul.........
    Route::get('/create_user_with_verification','UserController@registeruser');
    Route::get('/create_user_without_verification','UserController@registeruserwithout');
    Route::get('/verified_email/{email}/{token}','UserController@verified_email')->name('verified_email');
//endof login system by matul......
    Route::post('/profile', 'UserController@updatePic')->name('updatePic');
    Route::post('/updateUser', 'UserController@updateUser')->name('updateUser');
    Route::get('/user-search', 'UserController@search')->name('user-search');
    Route::get('/user-search-filter', 'UserController@searchforfilter')->name('user-search-filter');

    Route::get('/upcoming_services', 'PageController@upcomingServices')->name('upcomingServices');


    //My Posts
    Route::get('/my_posts', 'PageController@myPosts')->name('myPosts');
    Route::get('saved_posts', 'PageController@getSavePost')->name('getSavePost');
    //Coupon
    Route::get('/coupon', 'CouponController@coupons')->name('coupons');
    Route::get('/coupon/action', 'CouponController@action')->name('coupon.action');
    Route::get('/coupon/create', 'CouponController@create')->name('coupon.create');
    Route::post('/coupon/create', 'CouponController@store')->name('coupon.store');
    Route::get('/coupon/{id}/edit', 'CouponController@editCoupon')->name('coupon.edit');
    Route::post('/coupon/{id}/update', 'CouponController@updateCoupon')->name('coupon.update');
    Route::get('/coupon/{id}/delete', 'CouponController@deleteCoupon')->name('coupon.delete');


    // All Order details
    //Show All Orders
    Route::get('/order', 'OrderController@index')->name('order');
    //Buyer order from single buyer post
    Route::PUT('/buyerOrder/{id}', 'OrderController@buyerOrder')->name('buyerOrder');
    Route::get('/buyerShow/{id}', 'OrderController@buyerShow')->name('buyerShow');
    Route::get('/buyerSingle/{id}', 'OrderController@buyerSingle')->name('buyerSingle');
    Route::PUT('/buyerStatus/{id}', 'OrderController@buyerStatus')->name('buyerStatus');
    //Seller order from single seller post
    Route::PUT('/sellerOrder/{id}', 'OrderController@sellerOrder')->name('sellerOrder');
    // Route::get('/sellerShow/{id}', 'OrderController@sellerShow')->name('sellerShow');
    Route::get('/sellerSingle/{id}', 'OrderController@sellerSingle')->name('sellerSingle');
    Route::PUT('/sellerStatus/{id}', 'OrderController@sellerStatus')->name('sellerStatus');
    //Posts (buyer, seller, article)
    Route::resource('/buyer', 'BuyerController');
    Route::resource('/seller', 'SellerController');
    Route::resource('/article', 'ArticleController');
    //email
    Route::resource('/email', 'EmailController');


});
//Waqas Changes
Route::middleware(['auth'])->group(function () {
    Route::post('user-access-ajax', 'PageController@userAccessAjax')->name('UserAccessAjax');
    Route::post('edit-or-create-new-user', 'PageController@saveExistingUser')->name('saveExistingUser');
    Route::post('create-user/{flag}', 'PageController@CreateUserWith')->name('CreateUserWith');
    Route::post('delete-user', 'PageController@deleteProfile')->name('deleteProfile');

});

//Routes for advertisement

Route::get('/advertisement', 'AdvertisementController@index')->name('AdvertisementPage');

Route::post('/AdvertisementAction', 'AdvertisementController@action')->name('AdvertisementAction');
Route::get('/advertisement/show', 'AdvertisementController@viewAds')->name('AdvertisementShow');
Route::post('deleteAdd', 'AdvertisementController@deleteAdd')->name('deleteAdd');
Route::post('getAdsData', 'AdvertisementController@getAdsData')->name('getAdsData');
Route::post('addProfession', 'PageController@addProfession')->name('addProfession');
Route::post('getProfession', 'PageController@getProfession')->name('getProfession');
Route::post('updateProfession', 'PageController@updateProfession')->name('updateProfession');
Route::post('deleteProfession', 'PageController@deleteProfession')->name('deleteProfession');
Route::post('getProfessionOfType', 'PageController@getProfessionOfType')->name('getProfessionOfType');
Route::post('submitMembershipForm', 'PageController@submitMembershipForm')->name('submitMembershipForm');


Route::get('foo', function () {
    return 'Hello World';
});

/////////////////// ///////////////////////////////////
///////////////////////// Abdul Rehman Code ///////////////////////

Route::get('/faqsetup', 'FaqController@faqs')->name('faqs');
Route::get('/faq', 'FaqController@faquser')->name('faquser');
Route::post('/faqsetup/create', 'FaqController@store')->name('faq.store');
Route::get('/faqsetup/{id}/delete', 'FaqController@deleteFaq')->name('faq.delete');

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div id="columns">
                @isset($buyers)
                    @foreach ($buyers as $buyer)
                        <figure class="share-save-icon">
                            <img class="share-save-icon-buyr w-4"  style="" src="{{asset('img/' . 'referrer.png')}}">

                            <img id="{{$buyer->id}}" data-value="{{$id}}" data-value1="buyer" data-value-2="blue" class="share-save-icon-buyr w-4 m-2-45 blue <?php if($buyer->buyer_saved_status == 1){ ?>  hide  <?php } ?>"  style="" src="{{asset('img/' . 'save2.png')}}">
                            <img id="{{$buyer->id}}" data-value="{{$id}}" data-value1="buyer" data-value-2="yellow" class="share-save-icon-buyr w-4 m-2-45 yellow <?php if($buyer->buyer_saved_status == 0){ ?>  hide  <?php } ?>"  style="" src="{{asset('img/' . 'save3.jpg')}}">
                            <?php
                            if($buyer->buyer_saved_status != 1 && $buyer->buyer_saved_status != 0)
                            {
                            ?>
                            <img id="{{$buyer->id}}" data-value="{{$id}}" data-value1="buyer" data-value-2="blue" class="share-save-icon-buyr w-4 m-2-45 blue"  style="" src="{{asset('img/' . 'save2.png')}}">
                            <?php
                            }
                            ?>
                            <a href="{{ route('buyer.show', $buyer->id) }}">
                                <img src="{{ asset('uploads/buyer/' . $buyer->buyer_featured_image) }}">
                                <figcaption><strong>{{ $buyer->buyer_pro_title }}</strong></figcaption>
                                <figcaption class="mt-2"><small class="text-muted">{{ date('M j, Y', strtotime($buyer->created_at)) }}</small></figcaption>
                                <figcaption class="float-left"><small class="text-muted"><strong>Buy</strong></small></figcaption>
                            </a>
                        </figure>
                    @endforeach
                @endisset
                @isset($sellers)
                        @foreach ($sellers as $seller)
                            <figure class="share-save-icon">
                                <img class="share-save-icon-buyr w-4" src="{{asset('img/' . 'referrer.png')}}">
                                <img id="{{$seller->id}}" data-value="{{$id}}" data-value1="seller" data-value-2="blue" class="share-save-icon-buyr w-4 m-2-45 blue <?php if($seller->seller_saved_status == 1){ ?>  hide  <?php } ?>"  style="" src="{{asset('img/' . 'save2.png')}}">
                                <img id="{{$seller->id}}" data-value="{{$id}}" data-value1="seller" data-value-2="yellow" class="share-save-icon-buyr w-4 m-2-45 yellow <?php if($seller->seller_saved_status == 0){ ?>  hide  <?php } ?>"  style="" src="{{asset('img/' . 'save3.jpg')}}">
                                <?php
                                if($seller->seller_saved_status != 1 && $seller->seller_saved_status != 0)
                                {
                                ?>
                                <img id="{{$seller->id}}" data-value="{{$id}}" data-value1="seller" data-value-2="blue" class="share-save-icon-buyr w-4 m-2-45 blue"  style="" src="{{asset('img/' . 'save2.png')}}">
                                <?php
                                }
                                ?>
                                <a href="{{ route('seller.show', $seller->id) }}">
                                    <img src="{{ asset('uploads/seller/' . $seller->seller_featured_image) }}">
                                    <figcaption><strong>{{ $seller->seller_pro_title }}</strong></figcaption>
                                    <figcaption class="mt-2"><small class="text-muted">{{ date('M j, Y', strtotime($seller->created_at)) }}</small></figcaption>
                                    <figcaption class="float-left"><small class="text-muted"><strong>Sell</strong></small></figcaption>
                                </a>
                            </figure>
                        @endforeach
                @endisset
                    @isset($articles)
                        @foreach ($articles as $article)
                            <figure class="share-save-icon">
                                <img class="share-save-icon-buyr w-4" src="{{asset('img/' . 'referrer.png')}}">
                                <img id="{{$article->id}}" data-value="{{$id}}" data-value1="article" data-value-2="blue" class="share-save-icon-buyr w-4 m-2-45 blue <?php if($article->article_saved_status == 1){ ?>  hide  <?php } ?>"  style="" src="{{asset('img/' . 'save2.png')}}">
                                <img id="{{$article->id}}" data-value="{{$id}}" data-value1="article" data-value-2="yellow" class="share-save-icon-buyr w-4 m-2-45 yellow <?php if($article->article_saved_status == 0){ ?>  hide  <?php } ?>"  style="" src="{{asset('img/' . 'save3.jpg')}}">
                                <?php
                                if($article->article_saved_status != 1 && $article->article_saved_status != 0)
                                {
                                ?>
                                <img id="{{$article->id}}" data-value="{{$id}}" data-value1="article" data-value-2="blue" class="share-save-icon-buyr w-4 m-2-45 blue"  style="" src="{{asset('img/' . 'save2.png')}}">
                                <?php
                                }
                                ?>
                                <a href="{{ route('article.show', $article->id) }}">
                                    <img src="{{ asset('uploads/article/' . $article->article_featured_image) }}">
                                    <figcaption><strong>{{ $article->article_title }}</strong></figcaption>
                                    <figcaption class="mt-2"><small class="text-muted">{{ date('M j, Y', strtotime($article->created_at)) }}</small></figcaption>
                                    <figcaption class="float-left"><small class="text-muted"><strong>Article</strong></small></figcaption>
                                </a>
                            </figure>
                        @endforeach
                    @endisset



            </div>
        </div>
    </div>

    <div class="row">
        @isset($result)
            @foreach($result as $res)
                <div class="col-md-3    ">
                    <div class="card text-center card-width">
                        <div class="card-header filter">
                            <div class="row no-margin" style="width: 100%">
                                <div class="col-md-2" style="padding-right: 0; padding-left: 2px">
                                    <div class="img-container">
                                        <img width="100%" src="{{ url('/uploads/avatars').'/' . $res['user_pic'] }}">
                                    </div>
                                </div>
                                <div class="col-md-5" style="padding-left: 0;text-align: left">
                                    <div class="title-container ml-2"><span style="position: absolute;bottom: 0;">{{ $res['user_name'] }}</span></div>
                                </div>
                                <div class="col-md-5 align-self-end">
                                    <input id="ownRatingMobileCard" name="ownRating" class="rating rating-loading own-rating rating-xs ownRatingMobileCard"
                                           value="{{averageReview($res['user_id'])}}" style="padding-top: 8px;">

                                </div>
                            </div>

                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col">
                                    <img width="100%" src="{{url('/uploads') .$res['image']}}">
                                </div>
                            </div>
                            <h5 class="card-title">{{$res['heading']}}</h5>
                        </div>
                        <div class="card-footer text-muted">
                            {!!  $res['btn'] !!}
                        </div>
                    </div>
                </div>
            @endforeach
        @endisset


        {{--<div class="col-md-3">--}}
            {{--<div class="card text-center card-width">--}}
                {{--<div class="card-header">--}}
                    {{--<div class="row no-margin" style="width: 100%">--}}
                        {{--<div class="col-md-2" style="padding-right: 0; padding-left: 2px">--}}
                            {{--<div class="img-container">--}}
                                {{--<img width="100%" src="http://hi5working.test/uploads/avatars/1542355689.jpg">--}}
                            {{--</div>--}}
                        {{--</div>--}}
                        {{--<div class="col-md-5" style="padding-left: 0;text-align: left">--}}
                            {{--<div class="title-container ml-2"><span style="position: absolute;bottom: 0;">Elu</span></div>--}}
                        {{--</div>--}}
                        {{--<div class="col-md-5 align-self-end">--}}
                            {{--<input id="ownRatingMobileCard" name="ownRating" class="rating rating-loading own-rating rating-xs ownRatingMobileCard"--}}
                                   {{--value="{{averageReview(Auth::user()->id)}}" style="padding-top: 8px;">--}}

                        {{--</div>--}}
                    {{--</div>--}}

                {{--</div>--}}
                {{--<div class="card-body">--}}
                    {{--<div class="row">--}}
                        {{--<div class="col">--}}
                            {{--<img width="100%" src="http://hi5working.test/uploads/avatars/1542355689.jpg">--}}
                        {{--</div>--}}
                    {{--</div>--}}
                    {{--<h5 class="card-title">Elu@Elu.com</h5>--}}
                {{--</div>--}}
                {{--<div class="card-footer text-muted">--}}
                    {{--<a href="#" class="btn btn-primary">Go somewhere</a>--}}
                {{--</div>--}}
            {{--</div>--}}
        {{--</div>--}}


    </div>
</div>
@endsection
@section('extra-JS')
<script>

    $( document ).ready(function() 
    {
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
       $(".share-save-icon-buyr").click(function()
       {
            var user_id = $(this).attr("data-value");
            var post_id =  $(this).attr("id");
            var post_type =  $(this).attr("data-value1");
            var saved_cls = $(this).attr("data-value-2");
            var status = "";
            if(saved_cls == "blue"){
                $(this).addClass('hide');
                $(this).next().removeClass('hide');
                // $(".blue").addClass('hide');
                // $(".yellow").removeClass('hide');
                status = 1;
            }
            else
            {
                $(this).addClass('hide');
                $(this).prev().removeClass('hide');
                // $(".yellow").addClass('hide');
                // $(".blue").removeClass('hide');
                status = 0;
            }
           $.ajax({
                    url: "SavePost",
                    type: "POST",
                    data: {user_id : user_id, post_id:post_id, post_type:post_type,status:status},
                    dataType: "JSON",
                    success: function (data) {
                            console.log(data); 
                           
                        },
                        error: function(XMLHttpRequest, textStatus, errorThrown) {
                            alert('Something went wrong');
                        }
                });
       });
    });

    function showMsg(heading, amount,owner_id,id){
        Swal.fire({
            title: 'Pay To Read?',
            text: "You have to pay $"+amount+ " to read!",
            type: 'warning',
            showCancelButton: true,
            confirmButtonColor: 'green',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Pay'
        }).then((result) => {
            if (result.value) {
                $.ajax({

                    url: '/blog/pay-to-read/'+amount+'/'+owner_id,
                    type: 'GET',

                    success: function (response) {

                        console.log(response);
                        Swal.fire(
                            'Payment Done!',
                            'You can now read blog.',
                            'success'
                        ).then((result) => {
                            if (result.value) {
                                window.location = '/blod-details/'+id;
                            }
                        });

                    }
                });
            }
        });
    }
</script>

@endsection